### ISSUE TITLE
Gdb related build failure

### ISSUE THREAD

**Issue by lpapp-polatis** [MentorEmbedded/meta-sourcery#14]
WARNING: Host distribution "arch-rolling" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Parsing recipes: 100% |######################################################################################################################################################################################################| Time: 00:00:16
Parsing of 906 .bb files complete (0 cached, 906 parsed). 1235 targets, 45 skipped, 0 masked, 0 errors.

Build Configuration:
BB_VERSION        = "1.19.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "arch-rolling"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "beagleboard"
DISTRO            = "poky"
DISTRO_VERSION    = "1.4+snapshot-20130816"
TUNE_FEATURES     = "armv7a vfp neon"
TARGET_FPU        = "vfp-neon"
CSL_VER_MAIN      = "2009q1-203"
EXTERNAL_TOOLCHAIN = "/usr/local/arm-2009q1"
meta-sourcery     = "master:a7ee19cd79448c0a5f492a1244054f9999411522"
meta              
meta-yocto        
meta-yocto-bsp    
meta-networking   = "master:2db46232785f53067eb289d8da12cd4bf5eb4ea2"

NOTE: Resolving any missing task queue dependencies
NOTE: Preparing runqueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: Function failed: BUILDSPEC (log file is located at /home/lpapp/Projects/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/external-sourcery-toolchain/2009q1-203-r22/temp/log.do_package_write_rpm.16054)
ERROR: Logfile of failure stored in: /home/lpapp/Projects/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/external-sourcery-toolchain/2009q1-203-r22/temp/log.do_package_write_rpm.16054
Log data follows:
| DEBUG: Executing python function sstate_task_prefunc
| DEBUG: Python function sstate_task_prefunc finished
| DEBUG: Executing python function do_package_write_rpm
| DEBUG: Executing python function read_subpackage_metadata
| DEBUG: Python function read_subpackage_metadata finished
| DEBUG: Executing python function do_package_rpm
| DEBUG: Executing python function write_specfile
| NOTE: Not creating empty RPM package for linux-libc-headers
| NOTE: Not creating empty RPM package for linux-libc-headers-dev
| NOTE: Creating RPM package for gdbserver
| NOTE: Not creating empty RPM package for gdbserver-dbg
| NOTE: Creating RPM package for libstdc++6
| NOTE: Creating RPM package for libstdc++-dev
| NOTE: Creating RPM package for libstdc++-staticdev
| NOTE: Not creating empty RPM package for libquadmath
| NOTE: Not creating empty RPM package for libquadmath-dev
| NOTE: Not creating empty RPM package for libquadmath-staticdev
| NOTE: Not creating empty RPM package for libgomp
| NOTE: Not creating empty RPM package for libgomp-dev
| NOTE: Not creating empty RPM package for libgomp-staticdev
| NOTE: Creating RPM package for libgcc-s1
| NOTE: Creating RPM package for libgcc-s-dev
| NOTE: Creating EMPTY RPM Package for libc6-dbg
| NOTE: Creating RPM package for catchsegv
| NOTE: Creating RPM package for sln
| NOTE: Creating RPM package for nscd
| NOTE: Creating RPM package for ldd
| NOTE: Creating RPM package for eglibc-utils
| NOTE: Creating RPM package for libthread-db1
| NOTE: Not creating empty RPM package for eglibc-pic
| NOTE: Creating RPM package for libcidn1
| NOTE: Creating RPM package for libmemusage
| NOTE: Creating RPM package for libsegfault
| NOTE: Creating RPM package for eglibc-pcprofile
| NOTE: Not creating empty RPM package for libsotruss
| NOTE: Creating RPM package for libc6
| NOTE: Creating RPM package for eglibc-extra-nss
| NOTE: Creating RPM package for libc6-dev
| NOTE: Creating RPM package for eglibc-staticdev
| NOTE: Creating RPM package for eglibc-doc
| DEBUG: Python function write_specfile finished
| DEBUG: Executing shell function BUILDSPEC
| error: line 29: invalid tag value("^[A-Za-z0-9+._]+$") Version: Version: UNKNOWN(Execution of '/usr/local/arm+2009q1/bin/arm+none+linux+gnueabi+gdb +v' failed with exit code 127:
| error: Package has no %description: gdbserver.armv7a_vfp_neon
| Building target platforms: armv7a_vfp_neon-poky-linux-gnueabi
| DEBUG: Python function do_package_rpm finished
| DEBUG: Python function do_package_write_rpm finished
| ERROR: Function failed: BUILDSPEC (log file is located at /home/lpapp/Projects/poky/build/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/external-sourcery-toolchain/2009q1-203-r22/temp/log.do_package_write_rpm.16054)
ERROR: Task 80 (/home/lpapp/Projects/poky/meta-sourcery/recipes/meta/external-sourcery-toolchain.bb, do_package_write_rpm) failed with exit code '1'
NOTE: Tasks Summary: Attempted 388 tasks of which 384 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/lpapp/Projects/poky/meta-sourcery/recipes/meta/external-sourcery-toolchain.bb, do_package_write_rpm
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by kergoth** [comment]
With the new structure (multiple granular recipes, versions extracted by the recipe rather than parse time, etc), the version numbers don't fall back to UNKNOWN(<output>) in this way anymore, so this shouldn't occur anymore.

**Comment by lpapp-polatis** [comment]
OK, thanks, Chris.
