### ISSUE TITLE
meta-external-toolchain: systemd-boot.bbappend is not compatible with ccache

### ISSUE THREAD

**Issue by lumag** [MentorEmbedded/meta-sourcery#200]
Note, opening an issue for `meta-external-toolchain` against this repo, as suggested by layer's README.md.

`systemd-boot_%.bbappend` from `meta-external-toolchain` is not compatible with `ccache` class:
`-EFI_CC_tcmode-external = "${@'${CC}'.split()[0]} ${EFI_TUNE_ARCH}"` assignment will extract `ccache` from `${CC}` instead of extracting correct compiler.

Suggested change:
```patch
diff --git a/core/recipes-bsp/systemd-boot/systemd-boot_%.bbappend b/core/recipes-bsp/systemd-boot/systemd-boot_%.bbappend
index dbeb9c39f6fc..966a09e561db 100644
--- a/core/recipes-bsp/systemd-boot/systemd-boot_%.bbappend
+++ b/core/recipes-bsp/systemd-boot/systemd-boot_%.bbappend
@@ -3,5 +3,5 @@
 # external toolchain.
 EFI_TUNE_ARCH = "-m32"
 EFI_TUNE_ARCH_x86-64 = "-m64"
-EFI_CC_tcmode-external = "${@'${CC}'.split()[0]} ${EFI_TUNE_ARCH}"
+EFI_CC_tcmode-external = "${CCACHE}${HOST_PREFIX}gcc ${EFI_TUNE_ARCH}"
```

**Comment by kergoth** [comment]
Looks reasonable, the existing change was something of a hack, clearly. I'll see about changing it. Thanks. I may well move meta-external-toolchain to github with a git.yoctoproject.org mirror to ease workflows.. I'm not a big fan of email based patch distribution anymore :)

**Comment by kergoth** [comment]
Applied at https://git.yoctoproject.org/meta-external-toolchain/commit/?h=dunfell&id=540a295df8f71c3d19de25e4a914e2b635cd9032, thanks, sorry for the extreme delay.
