### ISSUE TITLE
What I should define in the script for the EXTERNAL_TOOLCHAIN_SETUP_SCRIPT

### ISSUE THREAD

**Issue by hizukiayaka** [MentorEmbedded/meta-sourcery#230]
I am working on support the Android NDK/VNDK building environment for OE. Then the android ndk would work as an external toolchain here.
I don't know what I should define in the script for the EXTERNAL_TOOLCHAIN_SETUP_SCRIPT, I can't find the document for it.

**Comment by kergoth** [comment]
This layer is only used for supporting Sourcery toolchains from Mentor Graphics / Siemens DISW, no others. See meta-external-toolchain if you're looking for a basic starting point on supporting a new external toolchain.
