### ISSUE TITLE
meta-sourcery is missing a dylan branch

### ISSUE THREAD

**Issue by alxn** [MentorEmbedded/meta-sourcery#25]
Given there is:
  remotes/origin/danny
  remotes/origin/dora
  remotes/origin/master

it would be nice to know the refpoint for the dylan branch as well.

**Comment by kergoth** [comment]
A dylan branch based on danny has been created, though it isn't likely to get much maintenance, at least the missing branch issue has been addressed.

**Comment by alxn** [comment]
@kergoth thanks.
