### ISSUE TITLE
To make Yocto SDK with meta-sourcery

### ISSUE THREAD

**Issue by iuhoac** [MentorEmbedded/meta-sourcery#34]
Hello:
--CPU：Intel ATOM 32bit 
--Yocto：poky-dylan-9.0.3
--toolchain：ia32-2012.09-62-i686-pc-linux-gnu-i386-linux

Modify
--Modify MACHINE = "qemux86" in conf/local.conf
--Add EXTERNAL_TOOLCHAIN = "path/to/ia32-2012.09_install" in conf/local.conf
--Add the meta-sourcery layer to my `BBLAYERS` in `conf/bblayers.conf`
When executing bitbake core-image-minimal -c populate_sdk,it will issue:
/path/to/ia32--2012.09/i686-pc-linux-gnu/bin/ld：cannot find crti.o：No such file or directory
/path/to/ia32--2012.09/i686-pc-linux-gnu/bin/ld：cannot find -lc
/path/to/ia32--2012.09/i686-pc-linux-gnu/bin/ld：cannot find crtn.o：No such file or directory

1.Does poky-dylan-9.0.3 support to make SDK with external toolchain of meta-sourcery?
2.if first problem say yes ,according to 4.2. Cross-Development Toolchain Generation of  mega-manual.html, why the task of do_compile gcc-cross-canadian will be failed?

                                                                                                                       Thank you!

**Comment by kergoth** [comment]
Unable to reproduce this behavior with current meta-sourcery.
